name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.5.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  buffer: ^1.2.3
  convert: ^3.1.1
  crypto: ^3.0.3
  http: ^1.0.0
  intl: ^0.19.0
  meta: ^1.10.0
  mime: ^1.0.5
  path: ^1.8.3
  xml: ^6.5.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  html: ^0.15.0
